version: '3.8'

services:
  node_app:
    image: node:latest
    working_dir: /usr/app
    ports:
      - "3000:3000"
    depends_on:
      - mysql_db
    volumes:
      - .:/usr/app
    command: sh -c "npm install && npm run start"

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "notas"
    volumes:
      - ./bbdd/notas.sql:/docker-entrypoint-initdb.d/notas.sql
